### PR TITLE
Adjusting format

### PR DESCRIPTION
**Pull request by sirop**
Some pieces of the previous manpage code did not render properly.

Do not know if any *asciidoc* format for functions was agreed upon, so let it be a proposal.

### CODE REVIEW

**Comment by ArcEye** [comment]
Can you remove the (3hm2) suffix in the title, it is irrelevant to asciidocs, just a hangover from the troff man pages.

I must get around to removing it from the contents of all the man1 and man3 files too :smile: . 
I have already removed it from the man1 and man3 filenames and it does not appear in any of the man9 files.

**Comment by sirop** [comment]
@ArcEye 

Removed.

But what about common style sheet for all functions' manpages?
Has such a thing been discussed?

**Comment by mhaberler** [comment]
not discusses so far but a great idea
no web experts here - can you start such a thing?

**Comment by ArcEye** [comment]
Not really.

If you look at the functions, they are just conversions into asciidoc.
You copied Andy Pughs functions formatting, but they were done for troff.

If you want to produce a template, that would be really useful, most of the functions need updating or even rewriting.

**Comment by ArcEye** [comment]
> I must get around to removing the suffixes from the contents of all the man1 and man3 files too :smile: . 

FYI -  I am on the case - mass sed slaughter being committed as we speak

**Comment by sirop** [comment]
What is used behind the curtain? Asciidoc or Asciidoctor?

As the output of each is customized differently.

**Comment by mhaberler** [comment]
asciidoctor as per https://github.com/mhaberler/docker-jekyll-asciidoctor

feel free to inspect https://jenkins.machinekit.io/view/machinekit/job/website-preview/ and https://jenkins.machinekit.io/view/machinekit/job/website-production

I might have to turn on permissions for you to view

**Pull request merged**
