### PR TITLE
Rename all asccidoc manual pages

### PR DESCRIPTION
**Pull request by ArcEye**
Rename all to the component or function they describe
without the legacy troff designations.

Pre-requisite to removal of all static man pages from the main machinekit repo

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by mhaberler** [comment]
the build both for preview and production is broken, in fact for several days

it looks like it's a change at github, and/or a plugin :-/

will get around to dig only later today

**Comment by ArcEye** [comment]
There is something wrong with github in general.  The server is very slow for simple look ups.

**Comment by mhaberler** [comment]
[github says it's all peachy ](https://status.github.com/) but I'm not buying it either

this push started failing after build 301, July 15
`````
+ git push --force origin HEAD:master
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
...
To ssh://machinekit-ci@github.com/machinekit/machinekit.github.io
 + 27e04a1...4d29104 HEAD -> master (forced update)
````

now it looks like so:

`````
+ git push --force origin HEAD:master
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`````

but there were no config changes in this time span: https://jenkins.machinekit.io/view/machinekit/job/website-production/jobConfigHistory/ and I was away so for sure did not update remotely

several jobs show the same pattern (auth fails)

**Comment by ArcEye** [comment]
It took 1 1/2 mins for this page to come up and a clone of a repo is being downloaded at 1024 Bp/s !

So definitely not rosy :stuck_out_tongue_winking_eye:

**Comment by ArcEye** [comment]
This has not helped
http://www.telegraph.co.uk/technology/2016/07/20/bt-down-broadband-service-suffers-major-outage-across-the-uk/
I don't use their DNS, which is apparently the only reason it is working at all.

**Comment by ArcEye** [comment]
Nudge - lets see if preview is working again

**Comment by ArcEye** [comment]
Nope, still fails.

The console output looks connected to what you posted previously, but I don't understand it :smile:

**Comment by mhaberler** [comment]
the only thing which fails is the status setting here, for reasons I do not get :-(

so merging anyway

**Pull request merged**
