### PR TITLE
a start at the infrastructure section

### PR DESCRIPTION
**Pull request by mhaberler**

### CODE REVIEW

**Comment by ArcEye** [comment]
The first heading in the doc needs a snappier title, it is used for the sidebar link and currently overflows into a second line.

selection_017

I will do a quick on-line amendment once the doc has been merged fully

**Comment by ArcEye** [comment]
Done  @ #182

**Comment by ArcEye** [comment]
Like the diagrams :+1:

**Comment by mhaberler** [comment]
yeah neat diagramming tools are a hobby of mine

there's quite a few tools already integrated in https://github.com/mhaberler/docker-jekyll-asciidoctor/blob/master/jekyll-asciidoctor-base/Dockerfile which I havent made a demo for yet:

http://www.gnuplot.info/
http://www.mcternan.me.uk/mscgen/ (but covered by seqdiag)
https://www.scipy.org
http://matplotlib.org/
http://pandas.pydata.org/pandas-docs/stable/
https://web.stanford.edu/~mwaskom/software/seaborn/
https://github.com/olgabot/prettyplotlib

I might add https://developers.google.com/chart/

**Comment by luminize** [comment]
> On 25 Jun 2016, at 17:25, Michael Haberler <notifications@github.com> wrote:
> 
> yeah neat diagramming tools are a hobby of mine
> 
Yes, very nice diagrams. Says more than words!
> http://www.mcternan.me.uk/mscgen/ (but covered by seqdiag)
> 
When the diagrams get a bit more complicated, like loops, then plantuml works very nice too.

**Pull request merged**
