### PR TITLE
diagram-examples.asciidoc: add PlantUML examples

### PR DESCRIPTION
**Pull request by luminize**
This will probably give errors. `jekyll-plantuml` needed to be installed. We'll see :)

### CODE REVIEW

**Comment by ArcEye** [comment]
Has indeed, I know how to add the gem on my own system, but not how to get it into the jekyll docker.

**Comment by mhaberler** [comment]
it's an automated build at https://hub.docker.com/r/haberlerm/docker-jekyll-asciidoctor/

file PR here: https://github.com/mhaberler/docker-jekyll-asciidoctor/blob/master/jekyll-asciidoctor-base/Gemfile, I merge, an hour later or so the  image is ready for pulling - this is integrated with dockerhub and autobuilds on merge

**Comment by luminize** [comment]
filed a PR.

**Comment by luminize** [comment]
I've re-run the build by filling in the SHA of the commit.
although there is a big "All checks have failed" above, the preview is fine.
http://preview.machinekit.io/docs/documenting/diagram-examples/#plantuml

so ready for a merge!

btw: @mhaberler very good workflow with the docker image!

**Comment by mhaberler** [comment]
yeah those builds need to be removed, the one one dockerhub counts, the rest is deprecated tests

**Comment by mhaberler** [comment]
the build on dockerhub went fine, a pull should get you the new image including the uml gem:

https://hub.docker.com/r/haberlerm/docker-jekyll-asciidoctor/builds/

**Pull request merged**
