### PR TITLE
Relative links - test PR

### PR DESCRIPTION
**Pull request by mhaberler**
let's see how this comes out on preview

I temporarily enabled the linkchecker on the preview job

### CODE REVIEW

**Comment by ArcEye** [comment]
typo in a script - missing `fi` in conditional if statement?

`/tmp/hudson8519426617618044622.sh: 53: /tmp/hudson8519426617618044622.sh: Syntax error: end of file unexpected (expecting "fi")`

**Comment by mhaberler** [comment]
yep, still massaging the jenkins job

the linkchecker is great but has some very arcane failure modes

**Comment by mhaberler** [comment]
I think this is good to merge, 1 bad link left (http://www.can-cia.org/fileadmin/cia/files/icc/13/kleine-budde.pdf in CAN-Developing

I checked it on my testbox

**Comment by ArcEye** [comment]
http://events.linuxfoundation.org/sites/events/files/slides/elce2013-Kleine-Budde.pdf
is a valid link and being linuxfoundation, more likely to persist

I replied on the wrong page initially:)

**Comment by ArcEye** [comment]
Ooops

**Pull request merged**
