### PR TITLE
instruction: how to frame a proper support question

### PR DESCRIPTION
**Pull request by luminize**
instructions on how to correctly get help when getting into trouble

### CODE REVIEW

**Comment by luminize** [comment]
like this? https://github.com/luminize/machinekit-docs/commit/51a76cc6ae9945028a93667dba58f4597e5dd76a#diff-cc00addcd7138aa12abc87adc53e0470R39

**Comment by mhaberler** [comment]
well searching the issue is one thing and certainly should be among the steps suggested

the decision which we need to make is: have them report on the list, or have them go straight to the issue tracker and file there

I think suggesting a straight tracker entry is more useful long-term - all issues in one place vs the list vs tracker dilution

not totally sure though

**Comment by luminize** [comment]
depends where you want sopport originating from. I think there's more people following the list then the issue tracker.
both cases you want people having read their own log file plus a logfile with pastebin link

if it's first on the list, and should be an issue we can alwask ask to make an issue out of it.

These instructions are first and foremost for the non-initiated. Let's not make too many barriers.

**Comment by RunningLight** [comment]
Clearly a good idea. Some nits:

1) the github search pages have poor road signage. The user needs to understand that they actually return two sets of hits: one on a repo's code base and one on the same repo's issues tracker, as indicated in the little box in the upper left labeled `<> code` and `(i) issues`

2) the github search mechanisms are pretty crude: I just tried searching on two recent problems of mine and got a lot of irrelevant hits...sigh.

3) I lean toward Michael's thought that issues should go straight to the issues tracker but I am a confirmed pessimist. I'm sure it will get diluted if not polluted. I believe it will require frequent administrative cleaning.

Because of this, I suspect having users post straight to the list may be a useful first step in filtering out redundant questions and directing new issues to the tracker(s), not because more people read the list, but because it's a general-purpose hub. I say "tracker(s)" because, there being more than one repo in play, there is more than one tracker.

4) I'm sure we'll have to flesh out the upfront requirement for information beyond asking the output of `uname -r` (why not `uname -a` by the way?) but it isn't clear to me how much to ask for before knowing the context. I'm thinking both hardware and software environments, not to mention info about the *Machinekit* the user actually has.

5) Am I a romantic to think that, over time, we might filter recurring themes into a FAQ to be perused before any of this?

**Comment by mhaberler** [comment]
@RunningLight - be unromantic - send a PR ;)

**Comment by luminize** [comment]
this PR is about instructions for the non-initiated getting help. Their effort should be to provide a minimal set of information for supporters to have a basic and proper starting point. A frequent question of a supporter is : Where's the pastebin of /var/log/linuxcnc.log ? What's happening ?

Plus, it's about teaching people that they are not stupid and _can_ solve some own problems. Read the log on their own. Giving them just a wee bit more self-confidence.

IMO it's up to the people giving support to narrow down when at first glance the cause for a problem doesn't show itself.

Let's not fall for the risk that we now need to decide about everything. That's what the C4 process is for.

Mind, I don't mean to sound pedantic (it's just that reading comes across differently than having a conversation) but I can think of loads of stuff to write about, which will take days, which nobody has time for. So as a result it doesn't happen at all and we all wail that the documentation is never op to date. So harness the power of enabling various contributors to extend on each others words... in small bits...

point 1 of http://www.machinekit.io/docs/C4/ section Development process:
> Change on the project SHALL be governed by the pattern of accurately identifying problems and applying minimal, accurate solutions to these problems

**Comment by RunningLight** [comment]
So what's the point of comments here? I thought they were a way to get the OP to amend the PR to incorporate improvements before merge. I'll stop commenting.

**Comment by luminize** [comment]
With all respect guys, "might", "think" or "not sure" just doesn't do it for me (the OP). What should the effect of a "suggestion" be? Then why instead of "suggesting" it, tell me because I can't look into your minds.
* Post a PR against my branch
* Tell me what is needed to get it merged or
* close the PR.

**Pull request merged**
