### PR TITLE
motion.asciidoc: fix lost front matter and synopsis

### PR DESCRIPTION
**Pull request by luminize**
this is a rebase and takes care of https://github.com/machinekit/machinekit-docs/pull/203 https://github.com/machinekit/machinekit-docs/pull/204 and https://github.com/machinekit/machinekit-docs/pull/205

### CODE REVIEW

**Comment by luminize** [comment]
wait a bit with the merge, because the "synopsis" line is strangely rendered/broken up

**Comment by ArcEye** [comment]
Can you get rid of the (9) at the top and (1) at the bottom of motion.asciidoc too please.

I removed all the other troff man page directory designations from the manual docs recently.

**Comment by luminize** [comment]
Sure, no problem

**Comment by luminize** [comment]
finally I have overcome a struggle where double asterixes, double underscores and whatnot had very strange behaviour where part of the line under "synopsis" wasn't rendered correctly.
PR is good to go!

**Comment by mhaberler** [comment]
much improved!

**Pull request merged**
