### PR TITLE
docs/basic_hal.asciidoc: make diagram example and improve `net`

### PR DESCRIPTION
**Pull request by luminize**
- removal of images
- addition od blockdiag example
- various improvements on `net` explanation

### CODE REVIEW

**Comment by mhaberler** [comment]
bizarre, the check and the job says 'successful' but I do not see the change on preview, do you?

must be this damn incremental flag which gets it wrong

**Comment by mhaberler** [comment]
well let's merge it and see what the www.machinekit.io site looks like

**Comment by luminize** [comment]
> On 27 May 2016, at 14:52, Michael Haberler <notifications@github.com> wrote:
> 
> well let's merge it and see what the www.machinekit.io site looks like
> 
The site looks good, but preview.machinekit.io doesn't show the change... Strange.

**Comment by mhaberler** [comment]
AFAICT both builds trigger; they just take a looong time (15min or so)

and for a reason I do not understand, a PR triggers _2 preview format runs_ instead of one..

**Pull request merged**
