### PR TITLE
add instructions for downloading the RCN image

### PR DESCRIPTION
**Pull request by luminize**

### CODE REVIEW

**Comment by luminize** [comment]
@mhaberler @ArcEye 
are we set and go w.r.t. changing this page http://www.machinekit.io/docs/packages-debian/ and this page http://www.machinekit.io/docs/building-from-source/ to a short 1-paragraph introduction with a link to the proper sections in machinekit-docs?

**Comment by mhaberler** [comment]
meaning to be replaced by what?

**Comment by luminize** [comment]
this: https://github.com/machinekit/machinekit-docs/blob/master/machinekit-documentation/getting-started/getting-started-platform.asciidoc

**Comment by luminize** [comment]
has to do with this https://github.com/machinekit/machinekit.github.io/issues/39
and this https://github.com/machinekit/machinekit.github.io/issues/51
and also about the preventing fragmented instructions in various places and supporting documentation in 2 locations

**Comment by ArcEye** [comment]
I only got so far with the conversion of the linuxcnc /src documents
ie the Getting Started Manual and User Manual links, but that should not prevent you putting the instructions on the github docs and linking the website to it

**Comment by RunningLight** [comment]
If the proper instructions exist in the machinekit-docs repo, then I agree with Bas. No purpose is served by having them in two places (it's confusing to newbies now and will get out of hand in the future as changes are made asynchronously) and I no longer believe the github Pages approach is worth arguing for.

As I told Michael privately, I am on a personal "sabbtical" from machinekit in order to support two robotics teams at our local high school as they prepare to compete in the 2015-2016 US FIRST Tech Challenge. I shall return but don't have time to devote to machinekit docs at the moment.

**Comment by luminize** [comment]
can somebody merge this? or is there something not OK?

**Pull request merged**
