### PR TITLE
Created beaglebone getting started, and updated link

### PR DESCRIPTION
**Pull request by pauluzs**
review layout

### CODE REVIEW

**Comment by luminize** [comment]
@pauluzs I'll have a proper look when I'm up again tomorrow. Sorry for the delay,
Bas

**Comment by pauluzs** [comment]
Geen probleem,

 Als je dan even naar de layout wil kijken want die krijg ik niet lekker
voor elkaar.

Had dit zelf ruwweg in een textfile

Grts Paul

2015-03-19 23:38 GMT+01:00 Bas de Bruijn <notifications@github.com>:

> @pauluzs I'll have a proper look when I'm up again tomorrow. Sorry for the
> delay,
> Bas
>

**Comment by luminize** [comment]
@pauluzs I think we have to take a look at what you're trying to document. Could I make the suggestion that we take this PR and work from there to get some more structure in this instruction?

**Comment by pauluzs** [comment]
@luminize As I started with buying a beaglebone to control cnc aplications i noticed that lots of ¨getting started" information is scattered across the web, Normaly i put some instructions/notes in a file for personal use, although spending so much time on finding/learning i thought it would be a good thing to list this. If there is a default stucture you would like/provide i will do some more writeups

**Comment by luminize** [comment]
Hi @pauluzs All effort on improving the docs is much appreciated. And you are absolutely right that stuff is scattered across the web.
As you say, this is much like a personal instructions/note file and If i may make a suggestion then we could work towards a layout thats better readable. There is no default layout but if I were having to build for the first time I would prefer something like [sectioning like this](https://github.com/machinekit/machinekit-docs/blob/master/machinekit-documentation/setting-up/lineardelta-FDM-printer.asciidoc) Not to the letter of course :)

**Comment by luminize** [comment]
not a lot of activity
closing

**Pull request closed without merging**
