### PR TITLE
new xhc-whb04b-6 and hy_vfd documents

### PR DESCRIPTION
**Pull request by rubienr**
Hi folks,

I added some additional documents for the following components:
* xhc-whb04b-6 (created new man page) and
* hy_vfd (took the base from linuxcnc, finished the missing parts and fixed some errors).

See this pull request https://github.com/machinekit/machinekit/pull/1430 for more details.

br, raoul

### CODE REVIEW

**Comment by ArcEye** [comment]
I need to look at this properly in a bit.

man pages are generated, not written, so this is not displayed.  
This would probably be better as a straight document.

**Comment by ArcEye** [comment]
I have seen the xhc docs, they are previewed here
http://preview.machinekit.io/docs/drivers/xhc-whb04b-6/
For some reason the hy_vfd one doesn't show, but I will sort that out once the main PR
is merged.

**Comment by ArcEye** [comment]
I'll wait until the new full website is rendered after merge and see if the hy_vfd doc is visible.
If not I will fix that directly.
There may be a couple of other links needed, but I will do those in due course too.

Thanks for your contribution.

**Comment by ArcEye** [comment]
OK found the problem.
There was a C style copyright notice left in above the top lines, which didn't prevent it rendering in github, but Jekyll did not recognise it as a proper asciidoc and failed to convert to html

It is now at http://www.machinekit.io/docs/drivers/hy_vfd/
and the xhc at
http://www.machinekit.io/docs/drivers/xhc-whb04b-6/

Also added a couple of extra links so it can be found.

**Comment by rubienr** [comment]
Thank you for the support! 
* Now I see the tables are sticking out. I renderd with Asciidoctor.js in Chromium. Back then I thought a table might be a good idea. Now I doubt. Should that be refined?
* I think, on the xhc-whb04b-6 page (section authors), I should remove the link to my github account. Name is enough.

**Comment by ArcEye** [comment]
1.  The tables render just fine under Firefox, both under Linux and Windows.
     They make it very clear, so I would leave them.
2.  Yes I would remove anything that could be scraped and used for hacking attempts or spam

**Pull request merged**
