### PR TITLE
hm2_soc_ol.asciidoc

### PR DESCRIPTION
**Pull request by luminize**
fix doc for passing parameters to instance parameter

### CODE REVIEW

**Comment by ArcEye** [comment]
Are you sure about this?
I just looked at my config for my mill with a DE0-NANO-Soc and the line I have is
`newinst [HOSTMOT2](DRIVER) hm2-socfpga0 --  config=[HOSTMOT2](CONFIG)`

Must admit have not used it for ages and would need to look it up again, but a quick search

"...a double dash (--) is used in bash built-in commands and many other commands to signify the end of command options, after which only positional parameters are accepted."

**Comment by luminize** [comment]
No, I'm not sure. Let me check if 2 dashes work. So far loading 2 dashes seems to work, and no dashes does not :)

**Comment by the-snowwhite** [comment]
All my mksocfpga configs run with only 2 dashes

**Comment by luminize** [comment]
I’ll close this one. Guess I made a mistake :)

**Pull request closed without merging**
