### PR TITLE
bring in machinetalk-protobuf as git subtree and generate docs/machinetalk/protobuf.asciidoc

### PR DESCRIPTION
**Pull request by mhaberler**
front matter still missing

### CODE REVIEW

**Comment by mhaberler** [comment]
jeepers, the machinetalk-protobuf Makefile is doing too much.. we dont need no stinkin' C++ generated ;)

**Comment by mhaberler** [comment]
nope, seems the container is missing some protobuf package

**Comment by ArcEye** [comment]
I'll have to leave you with it, know nothing about protobuf.

Would help if we had some documentation  .................  :laughing:

**Comment by mhaberler** [comment]
the protobuf docs is second to none: https://developers.google.com/protocol-buffers/

enjoy ;)

**Pull request closed without merging**
