### PR TITLE
Amend docs to reflect availability of backported rt kernels in Jessie

### PR DESCRIPTION
**Pull request by ArcEye**
Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
Well it looks like the docker image name has changed since last pulled.
```
11:08:21 $ docker pull mhaberler/jekyll-asciidoctor:jenkins_1030_1032
11:08:23 Failed to pull Docker image mhaberler/jekyll-asciidoctor:jenkins_1030_1032
```
Now appears to be
https://hub.docker.com/r/haberlerm/docker-jekyll-asciidoctor/

Nothing is ever simple

**Comment by luminize** [comment]
Want me to merge or does something go awry?

**Comment by ArcEye** [comment]
Great, it looks like this docker image was a special one, generated with user UID and GID built in
There does not appear to be a backup and the generic one fails.
Going to have to try generating a new one - time permitting

**Comment by ArcEye** [comment]
The build does not finish because it needs a container pre-built with UID/GID set
Just tried doing that and get errors from Ubuntu having pulled support for the distro which was used for some reason.
The production-build has been failing for a while.

**Comment by ArcEye** [comment]
Hopefully resolved after updating the distro apt repo in the docker so it is able to pull new packages.
Jenkins pointed to a new docker image.
Going for a full rebuild to wipe any lingering artifacts from previous builds
Will take longer, but we can be sure it works afterwards (hopefully)

**Comment by ArcEye** [comment]
Hurrah it works, I have learnt far too much about docker recently, my head hurts!

Just let me update the website-production Jenkins job before you merge this please

**Comment by ArcEye** [comment]
OK, I have changed the docker image it uses and wiped the workspace.

The website-production has not worked for the last 5 days, hopefully it will now

**Pull request merged**
