### PR TITLE
Jessie instructions 2

### LINKED ISSUE #38: Installation on Jessie instructions are missing
When all is mature enough for Machinekit to be supported on Debian Jessie, the installation instructions should be updated.

reference machinekit  issue : https://github.com/machinekit/machinekit/issues/598

### PR DESCRIPTION
**Pull request by luminize**
This PR should contain all info on
- setting up on debian Jessie
- building an RT-PREEMPT 

needed for https://github.com/machinekit/machinekit/issues/598
fixes #38

### CODE REVIEW

**Comment by jpmoniz** [comment]
@luminize  Would you like me to merge this?  Working on installing a Jessie dev system and would like to flush your instructions out.

**Comment by luminize** [comment]
Yes please !

**Comment by jpmoniz** [comment]
Merged

**Comment by jpmoniz** [comment]
@luminize @ArcEye 

Works as advertised. The kernel building/patching section could use a bit of massaging, but other than that everything built and ran fine!

**Comment by luminize** [comment]
Wonderful!
I'm glad that works.
Thanks for the feedback.

**Pull request merged**
