### PR TITLE
_data/docs.yml: add reference to "about-this-site"

### PR DESCRIPTION
**Pull request by luminize**

### CODE REVIEW

**Comment by luminize** [comment]
that's strange, it doesn't show at preview.machinekit.io

**Comment by ArcEye** [comment]
I am just trying it in a local build

**Comment by ArcEye** [comment]
You need to remove the spaces between the front matter and the header like so
```
---
layout: docs
---
:imagesoutdir: docs/site/about-this-site
= How to use this website
```

Then you get it displayed

selection_004

**Comment by ArcEye** [comment]
Awfully complex this jekyll stuff, one line too many and nothing shows up and no warnings or errors either

**Comment by luminize** [comment]
> On 30 May 2016, at 15:02, ArcEye <notifications@github.com> wrote:
> 
> You need to remove the spaces between the front matter and the header like so
> 
> ---
> layout: docs
> ---
> :imagesoutdir: docs/site/about-this-site
> = How to use this website

that’s very strange that it works locally, and not in the preview.
I’ll update, one moment, right back

**Comment by luminize** [comment]
Hmm, that doesn't add up. I can view locally fine, with all the empty lines, but not on preview.machinekit.io
see this https://raw.githubusercontent.com/machinekit/machinekit-docs/master/docs/getting-help.asciidoc which also in the side navigation

**Comment by ArcEye** [comment]
I can get it displayed with or without spaces too locally, the level 0 header appears the important bit.
I'll merge and see what happens, worst it can do is not display

**Comment by luminize** [comment]
@ArcEye @mhaberler I'm seeing something very strange...
this side bar link _only_ shows when I visit the page @mhaberler just updated http://www.machinekit.io/docs/documenting/diagram-examples/

see the picture below (How to use this website)

screen shot 2016-05-30 at 20 24 16

strange, isn't it?

**Comment by mhaberler** [comment]
preview: the last PR wins. There is no history.
maybe that was it.

**Comment by mhaberler** [comment]
what I will try is to force a full rebuild by editing _config.yml . I _think_ this should cause one.

**Comment by mhaberler** [comment]
yep, taken care of

**Pull request merged**
