### PR TITLE
Re-format /man/man9 rtapi_ for readability and remove troff

### PR DESCRIPTION
**Pull request by ArcEye**
Several corrections to obvious errors, but probably wrong elsewhere too

Thats it, I am finished with manual pages!

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by luminize** [comment]
I bow to your perseverance! kudos!

**Comment by ArcEye** [comment]
There is a problem with the website-production  job in Jenkins

I changed website-preview to create `source/docs/man/man9/images` because I created a new folder for the images in stepgen

Looks like I didn't copy that bit over into production and every build has failed for the last few days.

If it is not that, I will have to look at it tomorrow to figure out the difference between preview and production

**Comment by mhaberler** [comment]
@ArcEye - that was a whale of a job - we are big-time indebted to your stamina!

**Comment by ArcEye** [comment]
Just building again, with a specific copy across of images to the .deb pseudo dir added to the script.
Didn't like a recursive copy for some reason.

Just checked the resultant package and everything where it should be.

Hurrah, it finally builds, I can go and have dinner!

**Pull request merged**
