### PR TITLE
plugins: show image scaling, use stock asciidoctor video tag

### PR DESCRIPTION
**Pull request by mhaberler**

### CODE REVIEW

**Comment by mhaberler** [comment]
this one is for @luminize 's humungeous screen shots ;)

**Comment by luminize** [comment]
Wonderfull! I'll use that for correcting the humongeousities (if that's a word) :)

**Comment by mhaberler** [comment]
designed to work with https://gist.github.com/mhaberler/ede68eae275c38a5364734c065a1b9c0

**Comment by luminize** [comment]
I guess I ultimately missed this PR and it has conflicts.

**Comment by ArcEye** [comment]
I got some very strange stuff from github when I first followed the link.

Is this OK for merge now?

**Comment by ArcEye** [comment]
Think there was some kind of github barf, said the PR didn't exist or files had been lost, but going through PR's showed it up properly - merging

**Pull request merged**
