### PR TITLE
_data/docs.yml: add reference to "about-this-site"

### PR DESCRIPTION
**Pull request by luminize**

### CODE REVIEW

**Comment by luminize** [comment]
hmm, doesn't show in preview.machinekit.io

**Comment by luminize** [comment]
ok, thru edit-me link, made a branch on machinekit instead of my own GH repo.

**Comment by ArcEye** [comment]
Does not have a level 0 (=) header, just level 1 (==)

**Comment by luminize** [comment]
> On 30 May 2016, at 14:26, ArcEye <notifications@github.com> wrote:
> 
> Does not have a level 0 (=) header, just level 1 (==)
> 

Plus the edit-me link does something strange when I want to commit. It doesn’t make a branch on my repo, but the machinekit/machinekit-docs

be right back via the “normal” way

**Comment by mhaberler** [comment]
well yes, have a look at config.yml - that is where the repo is specified

**Comment by mhaberler** [comment]
it could well be certain changes are not detected if running --incremental
in that case, I'd do a tickle edit on config.yml to change the timestamp, this forces a full rebuild (I think)

just watch in jenkins what its doing, that's why you have accounts ;)

**Comment by cdsteinkuehler** [comment]
On 5/30/2016 3:30 PM, Michael Haberler wrote:
> it could well be certain changes are not detected if running --incremental
> in that case, I'd do a tickle edit on config.yml to change the timestamp, this 
> forces a full rebuild (I think)
> 
> just watch in jenkins what its doing, that's why you have accounts ;)

I think what Bas is referring to is what happens to me.  Since I have
edit permissions on the Machinekit repository, when I click "edit this
page" (or *ANY* github edit link on a repo I have control over), the
default is to create a branch in *THAT* repo, not fork/branch/PR like
we would want for C4.

I think everything works OK for the casual user (who won't have push
rights to machinekit/machinekitdocs), but for MK developers we will
likely need to institute a standard workflow so we can remain true to
C4.  I've been generally OK with the flurry of self-merged commits
recently, since there have been lots of eyes reviewing the changes,
but I look forward to returning to the "don't merge your own commit"
workflow.  It's not just to get at least a minimal review of the
changes, it also helps to keep multiple people engaged and "invested"
in the changes.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
yes I know, I've been merging a few of my own recently 

you are right

**Comment by luminize** [comment]
Charles, you're right. That's exactly what I meant.

I'm pretty sure it worked as intended before. (Created branch on my luminize/machinekit-docs repo)I think something subtle changed, maybe permissions on GH. I'll create an issue for this.

**Comment by cdsteinkuehler** [comment]
On 5/30/2016 4:14 PM, Bas de Bruijn wrote:
> Charles, you're right. That's exactly what I meant.
> 
> I'm pretty sure it worked as intended before. (Created branch on my 
> luminize/machinekit-docs repo)I think something subtle changed, maybe 
> permissions on GH. I'll create an issue for this.

The same thing happens when I try to do a github edit of any of my
personal repositories.

I noticed this earlier but figured those of us with push access will
understand git enough to be able to do a conventional clone/edit/PR
loop like we do for everything else.  IMHO the main thing is that it's
easy for the causal contributor who now only needs to have a github
account.

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
I recommend admins+maintainers working on this is to add a second "Joe User" github account, ideally in a different browser 

that helps reproducing such errors

**Comment by luminize** [comment]
> I recommend admins+maintainers working on this is to add a second "Joe User" github account, ideally in a different browser
> 
> that helps reproducing such errors
> 
I don't understand. How can I reproduce an error when that account has no write access to the repo like my normal account?

It worked before, didn't it? Mick an me had access to your mhaberler/machinekit-docs repo, and we tested edit-me-button changes too on machinekit/machinekit-docs.

I'm not saying we need to fix it now. But this is not ideal.

**Comment by mhaberler** [comment]
@luminize I guess I misunderstood the problem

**Pull request closed without merging**
