### PR TITLE
Update gcode.asciidoc

### PR DESCRIPTION
**Pull request by strahlex**
Added links to example files

### CODE REVIEW

**Comment by ArcEye** [comment]
```
09:31:25 + git subtree pull --prefix machinetalk-protobuf machinetalk-protobuf master --squash
09:31:27 From https://github.com/machinekit/machinetalk-protobuf
09:31:27  * branch            master     -> FETCH_HEAD
09:31:27 error: cannot run editor: No such file or directory
09:31:27 error: unable to start editor 'editor'
09:31:27 Not committing merge; use 'git commit' to complete the merge.
09:31:27 Build step 'Conditional step (single)' marked build as failure
```

I am not sure what this actually means, probably need @mhaberler   to look at it.
Could be connected to recent changes or could just be a coincidental glitch

**Comment by ArcEye** [comment]
```
09:31:27 error: cannot run editor: No such file or directory
09:31:27 error: unable to start editor 'editor'
```
On reflection, I *think* this is git trying to open the default editor, as it does when you do a merge manually, giving you the opportunity to add comments to the stock message.

There should be some way to script it so that just commits without that step.
Will have to look at it later if @mhaberler does not beat me to it.

**Comment by mhaberler** [comment]
this seems to have done the trick:

https://jenkins.machinekit.io/view/machinekit/job/website-preview/jobConfigHistory/showDiffFiles?timestamp1=2016-07-13_11-16-40&timestamp2=2016-07-13_11-30-52

**Comment by ArcEye** [comment]
>  this seems to have done the trick:

That makes sense, set `-m "message"` and it won't ask you for one.

I'll merge this anyway, it does not actually affect what was failing and the last build your change prompted passed.

**Comment by mhaberler** [comment]
well protobuf.asciidoc is not updated in both -preview and -production. Sigh..

**Comment by mhaberler** [comment]
I think it is. @strahlex - does http://www.machinekit.io/docs/machinetalk/protobuf/ and http://preview.machinekit.io/docs/machinetalk/protobuf/ reflect recent edits?

**Comment by ArcEye** [comment]
This commit is certainly in preview and the main site now

The links in http://www.machinekit.io/docs/examples/gcode/ now point to the MK repo
whereas previously they were a relative link to the same dir

**Comment by strahlex** [comment]
@mhaberler yes

**Pull request merged**
