### PR TITLE
add machinetalk-protobuf subtree, integrate protobuf.asciidoc generation

### PR DESCRIPTION
**Pull request by mhaberler**

### CODE REVIEW

**Comment by mhaberler** [comment]
docker container missing python-protobuf - rebuilding https://hub.docker.com/r/haberlerm/docker-jekyll-asciidoctor/builds/

**Comment by luminize** [comment]
This PR has a fail.

**Comment by mhaberler** [comment]
yee-haw! good to go in round 1 ;)

**Comment by mhaberler** [comment]
the error is OK for now, the final container is still building at https://hub.docker.com/r/haberlerm/docker-jekyll-asciidoctor/builds/

once it's pulle, should work fine

**Pull request merged**
