### PR TITLE
Finish tidy and format /man9 components

### PR DESCRIPTION
**Pull request by ArcEye**
Mostly edited for consistency of formatting and appearence
plus a couple of factual updates, instances of 'Linuxcnc' etc

images added to stepgen man page to replace troff generated graphs

### CODE REVIEW

**Comment by ArcEye** [comment]
The image dir is not being copied over from source to output in Jenkins
Need to look at that.

**Comment by luminize** [comment]
@ArcEye would it be an option to use waveform generated images http://www.machinekit.io/docs/documenting/diagram-examples/#wavedrom-digital-timing-diagrams ?

**Comment by ArcEye** [comment]
It might be, feel free to amend with a jazzy image later. :smile: 
The problem now is that any image is not getting copied over.

I have changed the config slightly and will close and re-open the PR to force a rebuild and see what happens.
Don't merge yet

**Comment by ArcEye** [comment]
OK the problem are the links themselves.
The images are getting copied over to /output OK.
I have used a relative link to `image::images/waveform1.png` which worked locally.

Have to go out, unless you spot the problem, I will look at it probably Sunday

**Comment by ArcEye** [comment]
Sorted.  I tested out with asciidoc documents through the browser plugin.
Forgot that Jekyll creates a dir for every file in the _site, so the links had to be one level up
eg.` image::../images/waveform1.png`

Now works as intended

selection_033

**Pull request merged**
